import { useEffect, useMemo, useRef, useState } from 'react';
import { claimDailyReward, completePomodoro, completeTask, createTask, dateKey, deleteTask, exportData, importData, initialize, levelFor, purchase, restoreTask, saveSettings, snapshot, undoCompletion, updateProfile, updateTask, xpFor } from './services/plannerService';

const priorities = { high: 0, medium: 1, low: 2 };
const refresh = async (setData) => setData(await snapshot());
const download = (text) => { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([text], { type: 'application/json' })); link.download = `gamified-planner-${dateKey()}.json`; link.click(); URL.revokeObjectURL(link.href); };

export default function App() {
  const [data, setData] = useState(null), [page, setPage] = useState('dashboard'), [toast, setToast] = useState(null), [demo, setDemo] = useState(false);
  const [timerNow, setTimerNow] = useState(Date.now()); const importRef = useRef();
  const load = () => refresh(setData).catch((error) => setToast({ title: 'Local storage error', text: error.message, kind: 'error' }));
  useEffect(() => { initialize().then(setData).catch((error) => setToast({ title: 'Local storage error', text: error.message, kind: 'error' })); }, []);
  useEffect(() => { if (!toast) return; const t = setTimeout(() => setToast(null), 5000); return () => clearTimeout(t); }, [toast]);
  const settings = data?.settings?.[0], profile = data?.profiles?.[0], activeTimer = settings?.activeTimer;
  useEffect(() => { if (!activeTimer?.running) return; const t = setInterval(() => setTimerNow(Date.now()), 500); return () => clearInterval(t); }, [activeTimer?.running]);
  const remaining = activeTimer ? Math.max(0, activeTimer.endsAt - timerNow) : 0;
  useEffect(() => { if (activeTimer?.running && remaining === 0) finishFocus(); }, [remaining]); // timestamp is the source of truth
  const act = async (operation, message) => { try { await operation(); await load(); if (message) setToast(message); } catch (error) { setToast({ title: 'Could not save locally', text: error.message, kind: 'error' }); } };
  const finishFocus = () => activeTimer && act(() => completePomodoro(activeTimer), { title: 'Focus session complete', text: '+15 XP saved to your local ledger.' });
  const complete = (task) => act(() => completeTask(task.id), { title: 'Task completed', text: `+${xpFor(task.difficulty)} XP`, undo: () => act(() => undoCompletion(task.id), { title: 'Completion undone', text: 'The matching ledger entry was reversed.' }) });
  const startFocus = (task) => act(() => saveSettings({ activeTimer: { taskId: task?.id || null, taskTitle: task?.title || 'Independent focus', startedAt: Date.now(), endsAt: Date.now() + (settings.focusMinutes * 60000), duration: settings.focusMinutes, running: true } }), null).then(() => setPage('focus'));
  if (!data) return <main className="loading" aria-live="polite">Opening your private study room…</main>;
  const nav = [['dashboard','⌂','Today'],['tasks','✓','Tasks'],['focus','◷','Focus'],['calendar','▦','Calendar'],['collection','✦','Collection'],['stats','⌁','Stats'],['settings','⚙','Settings']];
  return <div className={`app theme-${profile.activeTheme}`}><aside className="rail"><div className="monogram">GP<span>LOCAL</span></div><nav>{nav.map(([id, icon, label]) => <button key={id} className={page===id?'selected':''} onClick={() => setPage(id)}><i>{icon}</i><span>{label}</span></button>)}</nav><div className="rail-bottom"><button className="demo-switch" onClick={() => { setDemo(!demo); setToast({title: !demo ? 'Demo preview' : 'Back to your data', text: !demo ? 'Demo mode is visual only; your IndexedDB records stay untouched.' : 'Your local records are shown again.'}); }}>{demo ? 'EXIT DEMO' : 'TRY DEMO'}</button><button className="avatar" onClick={() => setPage('settings')} aria-label="Open settings">{profile.avatar}</button></div></aside><main><header className="topbar"><div><p className="eyebrow">{demo ? 'DEMO MODE / YOUR DATA IS SAFE' : 'OFFLINE-FIRST / STORED ON THIS DEVICE'}</p><h1>{page === 'dashboard' ? `Good morning, ${profile.username}.` : page[0].toUpperCase()+page.slice(1)}</h1></div><div className="header-stats"><span>🔥 {profile.currentStreak} day streak</span><b>✦ {profile.totalXP.toLocaleString()} XP</b></div></header>
  {page==='dashboard' && <Dashboard data={data} profile={profile} onComplete={complete} onFocus={startFocus} />}
  {page==='tasks' && <Tasks data={data} onRefresh={load} onComplete={complete} onFocus={startFocus} toast={setToast}/>} {page==='focus' && <Focus timer={activeTimer} remaining={remaining} onStart={startFocus} onPause={() => act(() => saveSettings({activeTimer:{...activeTimer,running:!activeTimer.running,endsAt:Date.now()+remaining}}))} onFinish={finishFocus}/>} {page==='calendar' && <Calendar data={data}/>} {page==='collection' && <Collection data={data}/>} {page==='stats' && <Stats data={data}/>} {page==='settings' && <Settings profile={profile} settings={settings} onSave={(p)=>act(()=>saveSettings(p))} onProfile={(p)=>act(()=>updateProfile(p))} onExport={()=>exportData().then(download)} onImport={async e=>{const file=e.target.files?.[0];if(file&&confirm('Replace your current local planner data with this validated export?')) await act(()=>file.text().then(importData),{title:'Import complete',text:'Your local records were restored.'});}} importRef={importRef}/>} </main>
  {toast && <div className={`toast ${toast.kind||''}`} role="status"><div><strong>{toast.title}</strong><p>{toast.text}</p></div>{toast.undo && <button onClick={toast.undo}>Undo</button>}<button aria-label="Dismiss notification" onClick={()=>setToast(null)}>×</button></div>}</div>;
}
function TaskRow({task,onComplete,onFocus,onDelete}) { return <article className={`task-row priority-${task.priority}`}><button className="checkbox" aria-label={task.status==='completed'?`${task.title} is completed`:`Complete ${task.title}`} disabled={task.status==='completed'} onClick={onComplete}>{task.status==='completed'?'✓':''}</button><div><strong>{task.title}</strong><p>{task.subject} · {task.estimatedMinutes} min · <em>{task.difficulty}</em> · {task.priority}</p></div>{task.status==='pending'&&<button className="focus-button" onClick={onFocus}>Focus ↗</button>}{onDelete&&<button className="text-button" onClick={onDelete}>Delete</button>}</article> }
function Dashboard({data,profile,onComplete,onFocus}) { const tasks=data.tasks.filter(t=>t.dueDate===dateKey()), complete=tasks.filter(t=>t.status==='completed'), active=tasks.filter(t=>t.status==='pending').sort((a,b)=>priorities[a.priority]-priorities[b.priority]||a.sortOrder-b.sortOrder); const level=levelFor(profile.totalXP), base=(level-1)**2*100,next=level**2*100; const focus=data.pomodoro_sessions.reduce((n,s)=>n+(s.durationMinutes||0),0); return <div className="page-grid"><section className="hero-card"><div className="stamp">LEVEL {level}</div><h2>Make a little progress<br/>look like a grand expedition.</h2><div className="level-track"><span style={{width:`${((profile.totalXP-base)/(next-base))*100}%`}}/></div><p>{profile.totalXP.toLocaleString()} XP banked locally</p></section><section className="metric-board"><div><span>Today’s quests</span><b>{complete.length} / {tasks.length}</b><small>missions sealed</small></div><div><span>Deep work</span><b>{Math.floor(focus/60)}h {focus%60}m</b><small>recorded focus</small></div><div><span>Streak</span><b>🔥 {profile.currentStreak}</b><small>best: {profile.longestStreak} days</small></div></section><section className="paper-card quest-list"><header><div><p className="eyebrow">TODAY’S ITINERARY</p><h2>Pick your next thread.</h2></div></header>{active.length?active.slice(0,4).map(t=><TaskRow key={t.id} task={t} onComplete={()=>onComplete(t)} onFocus={()=>onFocus(t)}/>):<div className="empty"><b>No tasks yet.</b><p>Start small. Add your first study task.</p></div>}</section><section className="paper-card goals"><p className="eyebrow">DAILY RITUALS</p><h2>Today’s goals</h2><Goal done={complete.length>=3} label="Complete 3 tasks" detail={`${complete.length} of 3`}/><Goal done={focus>=60} label="Focus for 60 minutes" detail={`${focus} of 60 min`}/><Goal done={profile.currentStreak>0} label="Maintain your streak" detail="study activity recorded"/></section></div> }
function Goal({done,label,detail}) { return <div className={`goal ${done?'done':''}`}><span>{done?'✓':'○'}</span><div><strong>{label}</strong><small>{detail}</small></div></div> }
function Tasks({data,onRefresh,onComplete,onFocus,toast}) { const [query,setQuery]=useState(''),[filter,setFilter]=useState('active'); const visible=useMemo(()=>data.tasks.filter(t=>(filter==='all'||filter==='active'&&t.status==='pending'||filter==='completed'&&t.status==='completed'||filter==='high'&&t.priority==='high')&&`${t.title} ${t.description} ${t.subject}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>priorities[a.priority]-priorities[b.priority]||a.sortOrder-b.sortOrder),[data.tasks,query,filter]); const add=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await createTask({title:f.get('title'),difficulty:f.get('difficulty'),priority:f.get('priority'),subject:f.get('subject'),estimatedMinutes:f.get('minutes')});e.currentTarget.reset();await onRefresh();toast({title:'Task added',text:'Saved in IndexedDB on this device.'});}catch(error){toast({title:'Could not add task',text:error.message,kind:'error'});}}; const del=async t=>{await deleteTask(t.id);await onRefresh();toast({title:'Task deleted',text:'Removed from your local list.',undo:async()=>{await restoreTask(t);await onRefresh();toast({title:'Task restored',text:'Back in your local list.'});}})}; return <section className="task-page"><form className="quick-add" onSubmit={add}><input name="title" placeholder="Add a task…" maxLength="160" required/><select name="difficulty" aria-label="Difficulty"><option value="easy">Easy +10</option><option value="medium">Medium +20</option><option value="hard">Hard +30</option></select><select name="priority" aria-label="Priority"><option value="medium">Medium priority</option><option value="high">High priority</option><option value="low">Low priority</option></select><input name="subject" placeholder="Subject"/><input name="minutes" type="number" min="1" placeholder="Min"/><button>+ Add</button></form><div className="task-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="🔎 Search tasks, subjects, notes…"/><div>{['active','all','completed','high'].map(x=><button type="button" className={filter===x?'active-filter':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div><section className="paper-card task-catalog"><header><div><p className="eyebrow">MISSION CONTROL</p><h2>{filter==='completed'?'Completed tasks':'Your tasks'}</h2></div><span>{visible.length} found</span></header>{visible.length?visible.map(t=><TaskRow key={t.id} task={t} onComplete={()=>onComplete(t)} onFocus={()=>onFocus(t)} onDelete={()=>del(t)}/>):<div className="empty"><b>No matching tasks.</b><p>Start small: capture the next useful thing.</p></div>}</section></section> }
function Focus({timer,remaining,onStart,onPause,onFinish}) { const sec=Math.ceil(remaining/1000), value=timer?`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`:'25:00'; return <section className="focus-room"><div className="focus-corner">FOCUS ROOM<br/><small>one tab · one purpose</small></div><div className="timer-dial"><div><p>{timer?.running?'FOCUSING ON':'READY WHEN YOU ARE'}</p><h2>{timer?.taskTitle||'Choose one meaningful task'}</h2><strong>{value}</strong><span>Timer is restored from timestamps after refresh.</span><div className="timer-actions">{timer?<><button onClick={onPause}>{timer.running?'Pause':'Resume'}</button><button className="outline" onClick={onFinish}>Finish</button></>:<button onClick={()=>onStart()}>Begin focus</button>}</div></div></div></section> }
function Calendar({data}) { const [month,setMonth]=useState(new Date()); const first=new Date(month.getFullYear(),month.getMonth(),1),offset=(first.getDay()+6)%7,count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(); const [selected,setSelected]=useState(dateKey()); const activity=Object.fromEntries(data.activity_days.map(a=>[a.date,a])); const selectedTasks=data.tasks.filter(t=>t.dueDate===selected||t.completedAt?.slice(0,10)===selected); const a=activity[selected]; return <section className="calendar-page paper-card"><header><div><p className="eyebrow">ACTIVITY ATLAS</p><h2>{month.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2></div><div><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>←</button><button onClick={()=>setMonth(new Date())}>Today</button><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>→</button></div></header><div className="weekdays">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=><span key={d}>{d}</span>)}</div><div className="calendar-grid">{Array.from({length:offset+count},(_,i)=>{const d=i-offset+1;if(d<1)return <span key={i}/>;const key=dateKey(new Date(month.getFullYear(),month.getMonth(),d));return <button key={key} className={`${key===dateKey()?'today':''} ${activity[key]?.active?'active-day':''}`} onClick={()=>setSelected(key)}><b>{d}</b>{activity[key]?.active&&<small>●</small>}</button>})}</div><aside><h3>{new Date(`${selected}T12:00:00`).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</h3>{selectedTasks.map(t=><p key={t.id}>{t.status==='completed'?'✓':'○'} {t.title}</p>)}<hr/><p><b>Tasks:</b> {a?.tasksCompleted||0}</p><p><b>Focus time:</b> {a?.focusMinutes||0} min</p></aside></section> }
function Collection({data}) { return <section className="collection-page"><header><p className="eyebrow">THE CABINET OF SMALL WONDERS</p><h2>Collected places</h2><p>Every consistent day leaves you with something to keep.</p></header><div className="collection-grid">{data.postcards.map(c=>{const u=data.user_postcards.find(x=>x.postcardId===c.id)||{piecesUnlocked:0};return <article className="collection-card library" key={c.id}><div className="collection-art"><span>{c.name}</span></div><div><small>{c.rarity.toUpperCase()}</small><h3>{c.name}</h3><div className="piece-track"><span style={{width:`${u.piecesUnlocked/c.totalPieces*100}%`}}/></div><p>{u.piecesUnlocked} / {c.totalPieces} fragments</p></div></article>})}</div></section> }
function Stats({data}) { const p=data.profiles[0], done=data.tasks.filter(t=>t.status==='completed'), pom=data.pomodoro_sessions.filter(s=>s.completed), focus=pom.reduce((n,s)=>n+s.durationMinutes,0), subjects={};done.forEach(t=>subjects[t.subject]=(subjects[t.subject]||0)+1); return <section className="stats-page"><div className="stats-hero"><p className="eyebrow">YOUR PRODUCTIVITY</p><h2>Actual local records, not estimates.</h2><div className="stat-cells"><Metric value={p.totalXP} label="total XP"/><Metric value={done.length} label="tasks complete"/><Metric value={pom.length} label="pomodoros"/><Metric value={`${Math.floor(focus/60)}h`} label="hours focused"/><Metric value={`${p.currentStreak}d`} label="current streak"/></div></div><section className="paper-card subject-card"><h2>Study terrain</h2>{Object.entries(subjects).length?Object.entries(subjects).map(([name,n])=><div className="subject" key={name}><span>{name}</span><div><i style={{width:`${n/done.length*100}%`}}/></div><b>{n}</b></div>):<p>Complete tasks to build your subject breakdown.</p>}</section></section> }
function Metric({value,label}) { return <div><b>{value}</b><span>{label}</span></div> }
function Settings({profile,settings,onSave,onProfile,onExport,onImport,importRef}) { return <section className="settings-page"><div><p className="eyebrow">MAKE THE ROOM YOURS</p><h2>Settings</h2></div><section className="paper-card"><h3>Profile & appearance</h3><label>Username<input value={profile.username} onChange={e=>onProfile({username:e.target.value.slice(0,40)})}/></label><div className="theme-choices">{[['midnight','Midnight'],['forest','Forest'],['default','Default']].map(([id,label])=><button key={id} className={profile.activeTheme===id?'chosen':''} onClick={()=>onProfile({activeTheme:id})}><i/><span>{label}</span></button>)}</div></section><section className="paper-card"><h3>Focus rituals</h3><div className="settings-grid"><label>Focus duration<input type="number" min="1" value={settings.focusMinutes} onChange={e=>onSave({focusMinutes:Number(e.target.value)})}/></label><label>Short break<input type="number" min="1" value={settings.shortBreak} onChange={e=>onSave({shortBreak:Number(e.target.value)})}/></label><label>Long break<input type="number" min="1" value={settings.longBreak} onChange={e=>onSave({longBreak:Number(e.target.value)})}/></label></div></section><section className="paper-card"><h3>Your data</h3><p>Export contains every IndexedDB store. Import validates its complete shape before replacing local records.</p><button className="dark-button" onClick={onExport}>Export my data</button><button className="text-button" onClick={()=>importRef.current.click()}>Import data</button><input ref={importRef} hidden type="file" accept="application/json" onChange={onImport}/></section></section> }
