-- Gamified Study Planner V2. Apply with `supabase db push`.
create extension if not exists pgcrypto;
create type public.task_difficulty as enum ('easy','medium','hard');
create type public.task_priority as enum ('high','medium','low');
create type public.task_status as enum ('pending','completed');
create type public.repeat_kind as enum ('never','daily','weekdays','weekly','custom');

create table public.themes (id uuid primary key default gen_random_uuid(), name text unique not null, description text, preview text, price integer not null default 0 check(price >= 0), theme_config jsonb not null default '{}'::jsonb, active boolean not null default true);
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, username text not null default 'Scholar', avatar_url text, level integer not null default 1 check(level > 0), total_xp integer not null default 0 check(total_xp >= 0), current_streak integer not null default 0 check(current_streak >= 0), longest_streak integer not null default 0 check(longest_streak >= 0), active_theme_id uuid references public.themes(id), settings jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.recurring_tasks (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null check(char_length(title) between 1 and 160), description text, subject text, difficulty public.task_difficulty not null default 'easy', priority public.task_priority not null default 'medium', repeat_type public.repeat_kind not null default 'never', repeat_days integer[] not null default '{}', start_date date not null default current_date, end_date date, next_occurrence date not null default current_date, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.tasks (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null check(char_length(title) between 1 and 160), description text, subject text, difficulty public.task_difficulty not null default 'easy', priority public.task_priority not null default 'medium', status public.task_status not null default 'pending', due_date date, estimated_minutes integer check(estimated_minutes > 0), completed_at timestamptz, sort_order numeric not null default 0, recurring_task_id uuid references public.recurring_tasks(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check ((status = 'completed') = (completed_at is not null)));
create table public.xp_transactions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, amount integer not null check(amount <> 0), reason text not null, reference_type text not null, reference_id uuid, created_at timestamptz not null default now(), unique(user_id, reference_type, reference_id, reason));
create table public.activity_days (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, activity_date date not null, tasks_completed integer not null default 0, pomodoros_completed integer not null default 0, focus_minutes integer not null default 0, xp_earned integer not null default 0, active boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, activity_date));
create table public.pomodoro_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, task_id uuid references public.tasks(id) on delete set null, started_at timestamptz not null, ended_at timestamptz, duration_minutes integer not null check(duration_minutes > 0), completed boolean not null default false, created_at timestamptz not null default now());
create table public.daily_goals (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, goal_date date not null, goal_type text not null, target integer not null check(target > 0), progress integer not null default 0, completed boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, goal_date, goal_type));
create table public.achievements (id uuid primary key default gen_random_uuid(), name text unique not null, description text not null, icon text not null, category text not null, requirement_type text not null, requirement_value integer not null, xp_reward integer not null default 0);
create table public.user_achievements (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, achievement_id uuid not null references public.achievements(id) on delete cascade, unlocked_at timestamptz not null default now(), unique(user_id, achievement_id));
create table public.shop_items (id uuid primary key default gen_random_uuid(), name text unique not null, description text not null, icon text not null, price integer not null check(price >= 0), item_type text not null, metadata jsonb not null default '{}'::jsonb, active boolean not null default true);
create table public.user_inventory (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, item_id uuid not null references public.shop_items(id), quantity integer not null default 0 check(quantity >= 0), purchased_at timestamptz not null default now(), unique(user_id,item_id));
create table public.postcards (id uuid primary key default gen_random_uuid(), name text unique not null, description text not null, image_url text, rarity text not null, total_pieces integer not null default 8 check(total_pieces > 0), xp_reward integer not null default 100, active boolean not null default true);
create table public.user_postcards (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, postcard_id uuid not null references public.postcards(id), pieces_unlocked integer not null default 0 check(pieces_unlocked >= 0), completed boolean not null default false, completed_at timestamptz, unique(user_id,postcard_id));
create table public.daily_rewards (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, reward_date date not null, reward_type text not null, reward_value integer not null, claimed boolean not null default false, claimed_at timestamptz, unique(user_id,reward_date));

create index tasks_user_due_idx on public.tasks(user_id,due_date,status,sort_order); create index tasks_subject_idx on public.tasks(user_id,subject); create index tasks_completed_idx on public.tasks(user_id,completed_at desc); create index activity_user_date_idx on public.activity_days(user_id,activity_date desc); create index xp_user_created_idx on public.xp_transactions(user_id,created_at desc); create index recurring_next_idx on public.recurring_tasks(user_id,next_occurrence) where active;

alter table public.profiles enable row level security; alter table public.tasks enable row level security; alter table public.recurring_tasks enable row level security; alter table public.xp_transactions enable row level security; alter table public.activity_days enable row level security; alter table public.pomodoro_sessions enable row level security; alter table public.daily_goals enable row level security; alter table public.user_achievements enable row level security; alter table public.user_inventory enable row level security; alter table public.user_postcards enable row level security; alter table public.daily_rewards enable row level security;
-- Catalogues are publicly readable; mutation happens only in controlled migrations/service context.
alter table public.achievements enable row level security; alter table public.shop_items enable row level security; alter table public.postcards enable row level security; alter table public.themes enable row level security;
create policy "catalogue readable" on public.achievements for select using (true); create policy "shop readable" on public.shop_items for select using (active); create policy "postcards readable" on public.postcards for select using (active); create policy "themes readable" on public.themes for select using (active);
-- Standard ownership policies. Game records are intentionally client read-only; SECURITY DEFINER RPCs mutate them.
do $$ declare t text; begin foreach t in array array['tasks','recurring_tasks','xp_transactions','activity_days','pomodoro_sessions','daily_goals','user_achievements','user_inventory','user_postcards','daily_rewards'] loop execute format('create policy "own %1$s" on public.%1$I for select using (auth.uid() = user_id)', t); end loop; end $$;
create policy "own profile" on public.profiles for select using (auth.uid() = id); create policy "update own profile" on public.profiles for update using (auth.uid() = id) with check(auth.uid() = id);
create policy "create own task" on public.tasks for insert with check(auth.uid()=user_id); create policy "update own pending task" on public.tasks for update using(auth.uid()=user_id) with check(auth.uid()=user_id); create policy "delete own task" on public.tasks for delete using(auth.uid()=user_id);
create policy "create own recurring" on public.recurring_tasks for insert with check(auth.uid()=user_id); create policy "update own recurring" on public.recurring_tasks for update using(auth.uid()=user_id) with check(auth.uid()=user_id); create policy "delete own recurring" on public.recurring_tasks for delete using(auth.uid()=user_id);

create or replace function public.level_for_xp(p_xp integer) returns integer language sql immutable as $$ select greatest(1, floor(sqrt(greatest(p_xp,0)::numeric / 100))::int + 1) $$;
create or replace function public.award_xp(p_user uuid,p_amount integer,p_reason text,p_type text,p_ref uuid) returns boolean language plpgsql security definer set search_path=public as $$ begin insert into xp_transactions(user_id,amount,reason,reference_type,reference_id) values(p_user,p_amount,p_reason,p_type,p_ref) on conflict(user_id,reference_type,reference_id,reason) do nothing; if found then update profiles set total_xp=total_xp+p_amount, level=level_for_xp(total_xp+p_amount),updated_at=now() where id=p_user; return true; end if; return false; end $$;
create or replace function public.complete_task(p_task_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$ declare t tasks%rowtype; gained integer; d date:=current_date; begin select * into t from tasks where id=p_task_id and user_id=auth.uid() for update; if not found then raise exception 'Task not found'; end if; if t.status='completed' then return jsonb_build_object('already_completed',true); end if; gained := case t.difficulty when 'easy' then 10 when 'medium' then 20 else 30 end; update tasks set status='completed',completed_at=now(),updated_at=now() where id=t.id; perform award_xp(auth.uid(),gained,'task_'||t.difficulty,'task',t.id); insert into activity_days(user_id,activity_date,tasks_completed,xp_earned,active) values(auth.uid(),d,1,gained,true) on conflict(user_id,activity_date) do update set tasks_completed=activity_days.tasks_completed+1,xp_earned=activity_days.xp_earned+gained,active=true,updated_at=now(); update profiles set current_streak=(select count(*) from (select activity_date, activity_date-row_number() over(order by activity_date)::int as grp from activity_days where user_id=auth.uid() and active and activity_date<=d) s where activity_date=d group by grp order by max(activity_date) desc limit 1), longest_streak=greatest(longest_streak,current_streak),updated_at=now() where id=auth.uid(); return jsonb_build_object('xp',gained,'task_id',t.id); end $$;
create or replace function public.undo_task_completion(p_task_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$ declare t tasks%rowtype; gained integer; begin select * into t from tasks where id=p_task_id and user_id=auth.uid() for update; if not found or t.status <> 'completed' then raise exception 'Completed task not found'; end if; gained:=case t.difficulty when 'easy' then 10 when 'medium' then 20 else 30 end; update tasks set status='pending',completed_at=null,updated_at=now() where id=t.id; insert into xp_transactions(user_id,amount,reason,reference_type,reference_id) values(auth.uid(),-gained,'task_undo','task_reversal',t.id) on conflict do nothing; update profiles set total_xp=greatest(0,total_xp-gained),level=level_for_xp(greatest(0,total_xp-gained)),updated_at=now() where id=auth.uid(); update activity_days set tasks_completed=greatest(0,tasks_completed-1),xp_earned=greatest(0,xp_earned-gained),active=(tasks_completed-1>0 or pomodoros_completed>0) where user_id=auth.uid() and activity_date=t.completed_at::date; return jsonb_build_object('undone',true); end $$;
grant execute on function public.complete_task(uuid),public.undo_task_completion(uuid) to authenticated;

-- Profiles are created exactly once after signup, never from browser-provided IDs.
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,username) values(new.id, coalesce(new.raw_user_meta_data->>'username', split_part(new.email,'@',1),'Scholar')); return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- Seeded, extensible catalogues. Subsequent migrations can safely update these names.
insert into public.achievements(name,description,icon,category,requirement_type,requirement_value,xp_reward) values
('First Step','Complete your first task.','🏁','beginner','tasks_completed',1,20),('3 Day Warrior','Maintain a 3-day streak.','🔥','consistency','streak',3,30),('Week Warrior','Maintain a 7-day streak.','🔥','consistency','streak',7,50),('Month Machine','Maintain a 30-day streak.','🔥','consistency','streak',30,150),('Bookworm','Complete 50 tasks.','📚','productivity','tasks_completed',50,100),('Focused','Complete 10 Pomodoro sessions.','⏱️','productivity','pomodoros_completed',10,100),('Centurion','Earn 1,000 XP.','💯','productivity','total_xp',1000,150),('Collector','Complete your first postcard.','🃏','completion','postcards_completed',1,100),('Gallery Owner','Complete every postcard.','🃏','completion','all_postcards',1,250) on conflict(name) do nothing;
insert into public.shop_items(name,description,icon,price,item_type,metadata) values
('Streak Freeze','Protect one missed day without earning streak XP.','❄',500,'streak_freeze','{}'),('New Theme','Unlock an alternate study room palette.','◐',1000,'theme','{}'),('Special Postcard','Add a rare collection card.','✦',1500,'postcard','{}'),('2× XP Booster','Double the next five eligible task or focus rewards.','×2',750,'xp_booster','{"eligible_actions":5}'::jsonb),('Custom Profile Badge','A permanent profile flourish.','◆',1000,'badge','{}') on conflict(name) do nothing;
insert into public.themes(name,description,preview,price,theme_config) values
('Default','Warm archive paper and ink.','#25372e',0,'{"accent":"#d05b38"}'),('Midnight','A focused dark reading room.','#17232d',1000,'{"accent":"#f0a166"}'),('Forest','Moss, paper, and patient growth.','#36523b',1000,'{"accent":"#b9cc8d"}'),('Cyber','Electric night-study contrast.','#17152c',1000,'{"accent":"#e87dcb"}'),('Study Café','Terracotta and toasted cream.','#6b3b2d',1000,'{"accent":"#f1b66a"}') on conflict(name) do nothing;
insert into public.postcards(name,description,rarity,total_pieces,xp_reward) values ('Night Library','A lamplit shelf found through consistency.','rare',8,100),('Amber Observatory','A far-off desk under stars.','epic',8,100),('Moss & Margins','Notes tucked into a green afternoon.','common',8,100) on conflict(name) do nothing;

create or replace function public.complete_pomodoro(p_task_id uuid,p_started_at timestamptz,p_duration_minutes integer) returns jsonb language plpgsql security definer set search_path=public as $$ declare sid uuid:=gen_random_uuid(); begin if p_duration_minutes < 1 or p_duration_minutes > 180 then raise exception 'Invalid focus duration'; end if; if p_task_id is not null and not exists(select 1 from tasks where id=p_task_id and user_id=auth.uid()) then raise exception 'Task not found'; end if; insert into pomodoro_sessions(id,user_id,task_id,started_at,ended_at,duration_minutes,completed) values(sid,auth.uid(),p_task_id,p_started_at,now(),p_duration_minutes,true); perform award_xp(auth.uid(),15,'pomodoro','pomodoro',sid); insert into activity_days(user_id,activity_date,pomodoros_completed,focus_minutes,xp_earned,active) values(auth.uid(),current_date,1,p_duration_minutes,15,true) on conflict(user_id,activity_date) do update set pomodoros_completed=activity_days.pomodoros_completed+1,focus_minutes=activity_days.focus_minutes+p_duration_minutes,xp_earned=activity_days.xp_earned+15,active=true,updated_at=now(); return jsonb_build_object('xp',15,'session_id',sid); end $$;
create or replace function public.purchase_shop_item(p_item_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$ declare item shop_items%rowtype; begin select * into item from shop_items where id=p_item_id and active for update; if not found then raise exception 'Item unavailable'; end if; update profiles set total_xp=total_xp-item.price,level=level_for_xp(total_xp-item.price),updated_at=now() where id=auth.uid() and total_xp>=item.price; if not found then raise exception 'Insufficient XP'; end if; insert into xp_transactions(user_id,amount,reason,reference_type,reference_id) values(auth.uid(),-item.price,'shop_purchase','shop',gen_random_uuid()); insert into user_inventory(user_id,item_id,quantity) values(auth.uid(),item.id,1) on conflict(user_id,item_id) do update set quantity=user_inventory.quantity+1,purchased_at=now(); return jsonb_build_object('purchased',item.name,'price',item.price); end $$;
create or replace function public.claim_daily_reward() returns jsonb language plpgsql security definer set search_path=public as $$ declare rid uuid:=gen_random_uuid(); begin insert into daily_rewards(id,user_id,reward_date,reward_type,reward_value,claimed,claimed_at) values(rid,auth.uid(),current_date,'daily_xp',25,true,now()) on conflict(user_id,reward_date) do nothing; if not found then raise exception 'Today''s reward is already claimed'; end if; perform award_xp(auth.uid(),25,'daily_reward','daily_reward',rid); return jsonb_build_object('xp',25); end $$;
grant execute on function public.complete_pomodoro(uuid,timestamptz,integer),public.purchase_shop_item(uuid),public.claim_daily_reward() to authenticated;
